version: '3.6'

services:
  oye-api:
    container_name: backend
    build: ./
    command: npm start
    working_dir: /usr/src/oye-rickshaw
    environment:
      POSTGRES_URI: postgres://oye-rickshaw:password@postgres:5432/oye_rickshaw_db
      JWT_SECRET_KEY: jwtsecretkey
    links:
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/oye-rickshaw

  postgres:
    build: ./postgres
    environment:
      POSTGRES_USER: oye-rickshaw
      POSTGRES_PASSWORD: password
      POSTGRES_DB: oye_rickshaw_db
      POSTGRES_HOST: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data